// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

interface IERC20 {
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function transfer(address to, uint256 amount) external returns (bool);
}

// FundlineRunEscrow is a non-custodial, per-run workflow-billing escrow on Arc.
//
// A user pre-funds the fixed price of one AI workflow run from their OWN wallet
// (fund). Fundline's treasury key settles the run: on success it calls release,
// which pays the funded amount to the treasury and emits the InvoiceMemo receipt;
// on failure it calls refund, returning the funded amount to the payer. If the
// treasury goes silent after fund (for example the server dies between fund and
// release/refund), the payer can self-recover via claimRefund once REFUND_WINDOW
// has elapsed. The refund window is ONLY a stuck-funds backstop; the normal
// failure path is an immediate treasury refund.
//
// Non-custodial invariant (make or break): there is NO owner, admin, upgrade,
// or selfdestruct path. No privileged actor can withdraw, seize, or redirect
// escrowed funds. Funds move only by the contract's rules:
//   - payer    -> contract   on fund
//   - contract -> treasury   on release   (treasury-gated)
//   - contract -> payer      on refund    (treasury-gated) and claimRefund (payer, after deadline)
// No path sends to an arbitrary address or moves more than runs[runId].amount.
// There is NO fee: the full funded amount is released or refunded, never skimmed.
//
// Trust boundary (documented honestly): release is treasury-gated and CANNOT be
// proven on-chain to correspond to real workflow output. The user accepts this
// for a first-party fixed-price service. The contract still bounds treasury power
// to exactly "release the funded amount to the treasury, or refund it to the
// payer", and the refund window gives the payer recourse if the treasury never
// acts. It does NOT protect against a treasury that releases without delivering
// output (off-chain trust, the same as any prepaid service).
//
// Funds movement uses the USDC ERC-20 interface (IERC20.transferFrom / transfer
// against the Arc USDC system contract at 0x3600...0000), NOT msg.value. On Arc,
// USDC is also the native gas token; routing the escrowed amount through the
// ERC-20 interface keeps the funded amount exact and independent of the gas a
// caller separately spends. USDC has 6 decimals: all amounts here are raw base
// units and no decimal scaling is performed (do not assume 18 decimals).
contract FundlineRunEscrow {
    address public immutable usdc;
    address public immutable treasury;

    // Stuck-funds backstop window. The payer may self-refund after this elapses
    // if the treasury has neither released nor refunded the run.
    uint256 public constant REFUND_WINDOW = 1 hours;

    struct Run {
        address payer;          // the user who funded the run
        uint256 amount;         // fixed price, raw 6-decimal USDC base units
        uint64 refundDeadline;  // payer may claimRefund at or after this time
        bool released;          // funds paid to treasury
        bool refunded;          // funds returned to payer
    }

    // key = runId (server-generated bytes32). A run is terminally released XOR refunded.
    mapping(bytes32 => Run) public runs;

    event RunFunded(bytes32 indexed runId, address indexed payer, uint256 amount);
    event RunReleased(bytes32 indexed runId, address indexed payer, uint256 amount);
    event RunRefunded(bytes32 indexed runId, address indexed payer, uint256 amount);

    // Same signature and topic0 as FundlineMemoRouter.InvoiceMemo so the existing
    // indexer reads this contract's release receipts unchanged.
    event InvoiceMemo(
        bytes32 indexed invoiceId,
        address indexed payer,
        bytes memo
    );

    error InvalidAddress();
    error InvalidAmount();
    error RunExists();
    error UnknownRun();
    error NotTreasury();
    error NotPayer();
    error AlreadyReleased();
    error AlreadyRefunded();
    error RefundWindowOpen();
    error TransferFailed();

    constructor(address usdc_, address treasury_) {
        if (usdc_ == address(0) || treasury_ == address(0)) revert InvalidAddress();
        usdc = usdc_;
        treasury = treasury_;
    }

    // msg.sender is the payer. The payer must have approved this contract for
    // amount on the USDC token first. runId must be unused. Pulls amount from
    // the payer into escrow and records the run.
    function fund(bytes32 runId, uint256 amount) external {
        if (amount == 0) revert InvalidAmount();
        if (runs[runId].payer != address(0)) revert RunExists();

        runs[runId] = Run({
            payer: msg.sender,
            amount: amount,
            refundDeadline: uint64(block.timestamp + REFUND_WINDOW),
            released: false,
            refunded: false
        });

        bool ok = IERC20(usdc).transferFrom(msg.sender, address(this), amount);
        if (!ok) revert TransferFailed();

        emit RunFunded(runId, msg.sender, amount);
    }

    // Treasury settles a successful run: pays the funded amount to the treasury
    // and emits the workflow memo receipt. Checks-effects-interactions: released
    // is set before the external transfer.
    function release(bytes32 runId, bytes calldata memo) external {
        if (msg.sender != treasury) revert NotTreasury();
        Run storage run = runs[runId];
        if (run.payer == address(0)) revert UnknownRun();
        if (run.released) revert AlreadyReleased();
        if (run.refunded) revert AlreadyRefunded();

        run.released = true;

        bool ok = IERC20(usdc).transfer(treasury, run.amount);
        if (!ok) revert TransferFailed();

        emit InvoiceMemo(runId, run.payer, memo);
        emit RunReleased(runId, run.payer, run.amount);
    }

    // Treasury settles a failed run by returning the funded amount to the payer.
    // Checks-effects-interactions: refunded is set before the external transfer.
    function refund(bytes32 runId) external {
        if (msg.sender != treasury) revert NotTreasury();
        Run storage run = runs[runId];
        if (run.payer == address(0)) revert UnknownRun();
        if (run.released) revert AlreadyReleased();
        if (run.refunded) revert AlreadyRefunded();

        run.refunded = true;
        address payer = run.payer;
        uint256 amount = run.amount;

        bool ok = IERC20(usdc).transfer(payer, amount);
        if (!ok) revert TransferFailed();

        emit RunRefunded(runId, payer, amount);
    }

    // Payer safety net: if the treasury never released or refunded, the payer
    // may reclaim the funded amount once REFUND_WINDOW has elapsed. Only the
    // run's payer can call it, and only to refund themselves.
    function claimRefund(bytes32 runId) external {
        Run storage run = runs[runId];
        if (run.payer == address(0)) revert UnknownRun();
        if (msg.sender != run.payer) revert NotPayer();
        if (run.released) revert AlreadyReleased();
        if (run.refunded) revert AlreadyRefunded();
        if (block.timestamp < run.refundDeadline) revert RefundWindowOpen();

        run.refunded = true;
        uint256 amount = run.amount;

        bool ok = IERC20(usdc).transfer(run.payer, amount);
        if (!ok) revert TransferFailed();

        emit RunRefunded(runId, run.payer, amount);
    }

    function getRun(bytes32 runId)
        external
        view
        returns (
            address payer,
            uint256 amount,
            uint64 refundDeadline,
            bool released,
            bool refunded
        )
    {
        Run storage run = runs[runId];
        return (run.payer, run.amount, run.refundDeadline, run.released, run.refunded);
    }
}
